# -----------------------------------------------------------------------
# Alacritty Config
# 
# More Info: https://alacritty.org/config-alacritty.html
# -----------------------------------------------------------------------


[terminal.shell]
program = "C:\\Windows\\System32\\wsl.exe"
args = ["-d", "Ubuntu-24.04", "--cd", "~", "--user", "zaccsorny"]
# args = ["-d", "Ubuntu", "--cd", "~", "--", "zsh"]

[env]
#TERM = "alacritty"
# for terminal/tmux/nvim colorscheme consistency

TERM = "xterm-256color"


### Nord Color Theme ###

[colors.primary]
background = "#2e3440"
foreground = "#d8dee9"

dim_foreground = "#a5abb6"

[colors.cursor]
text = "#2e3440"
cursor = "#d8dee9"

[colors.vi_mode_cursor]
text = "#2e3440"
cursor = "#d8dee9"

[colors.selection]
text = "CellForeground"
background = "#4c566a"

[colors.search.matches]

foreground = "CellBackground"
background = "#88c0d0"


# [colors.search.bar]
# background = "#434c5e"
# foreground = "#d8dee9"

[colors.normal]
black = "#3b4252"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"

magenta = "#b48ead"
cyan = "#88c0d0"
white = "#e5e9f0"

[colors.bright]
black = "#4c566a"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#8fbcbb"
white = "#eceff4"

[colors.dim]
black = "#373e4d"
red = "#94545d"
green = "#809575"
yellow = "#b29e75"
blue = "#68809a"
magenta = "#8c738c"
cyan = "#6d96a5"
white = "#aeb3bb"



### Font ### 

# for windows, font must be listed at: Settings > Personalization > Fonts
[font]
size = 9


[font.normal]

family = "JetBrainsMono Nerd Font"
style = "ExtraLight"
# style = "Thin"
#style = "Light"

[font.bold]

family = "JetBrainsMono Nerd Font"
style = "SemiBold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Thin Italic"

#style = "Light Italic"

[font.bold_italic]

family = "JetBrainsMono Nerd Font"
style = "SemiBold Italic"


### Misc. ### 

[cursor]
style = "Beam"
# vi_mode_style = { <shape>, <blinking> } | "None"


[window]

title = "ZC"
# decorations
#	full: borders and title bar
# 	none: neither borders nor title bar
decorations = 'buttonless'
dynamic_padding = true

#startup_mode = "Fullscreen"

[scrolling]
# max scroll history: 100000
history = 14999
multiplier = 5

[selection]
save_to_clipboard = true

[debug]
persistent_logging = false
# supress WARNING messages
log_level = "Error"

# mouse scrolls are treated as page ups/downs instead
[mouse]
bindings = [
  { mouse = "WheelUp",   action = "ScrollLineUp" },
  { mouse = "WheelDown", action = "ScrollLineDown" },
]
