[sqlfluff]
dialect = postgres
templater = jinja
rules = layout, capitalisation
ignore = parsing, templating
fix_even_unparsable = True

# set value to '0' disable
large_file_skip_char_limit = 0
large_file_skip_byte_limit = 550000
max_line_length = 100

[sqlfluff:indentation]
indent_unit = space
tab_space_size = 2
indented_joins = False
indented_using_on = True
indented_ctes = True


## Layout Rules ## 

[sqlfluff:rules:layout.spacing]
no_trailing_whitespace = true
extra_whitespace = false

[sqlfluff:rules:layout.commas]
comma_style = trailing
line_position = trailing

[sqlfluff:rules:layout.functions]
no_space_after_function_name = true

[sqlfluff:layout:type:newline]
spacing_before = single
spacing_after = single

[sqlfluff:rules:layout.operators]
operator_new_lines = before

[sqlfluff:rules:layout.long_lines]
ignore_comment_lines = True
ignore_comment_clauses = True


[sqlfluff:rules:layout.set_operators]
set_operator_on_new_line = ['UNION', 'UNION ALL']


## Capitalization Rules ## 

[sqlfluff:rules:capitalisation.keywords]
capitalisation_policy = upper

[sqlfluff:rules:capitalisation.functions]
extended_capitalisation_policy = upper

[sqlfluff:rules:capitalisation.identifiers]
extended_capitalisation_policy = lower

[sqlfluff:rules:capitalisation.literals]
capitalisation_policy = lower

[sqlfluff:rules:layout.commas]
line_position = trailing

[sqlfluff:rules:layout.functions]
no_space_after_function_name = true


## Excluded Rules ##

[sqlfluff:rules]
exclude_rules = LT09, RF05, CP05
