# BAT (Command defaults) Configuraton File

# set theme to Nord
--theme="Nord"

# set pager flag to "less -RFK" (recommened setting per repo docs)
--pager="less -RFK"

# uncomment below to disable automatic paging
#--paging=never

# ignores ".dev" suffix
# example: bat will treat 'data.json.dev' as a JSON file
--ignored-suffix ".dev"
--ignored-suffix ".tmp"

# adding commonly used ignore suffixes
--ignored-suffix ".ignr"
--ignored-suffix ".gig"
--ignored-suffix ".ignored"


# adding commonly used archive/backup suffixes
--ignored-suffix ".bk"
--ignored-suffix ".ark"
--ignored-suffix ".cpy"


# 
--map-syntax ".conf:INI"
--map-syntax ".ignore:Git Ignore"
--map-syntax ".ignored:Git Ignore"
--map-syntax ".gig:Git Ignore"
--map-syntax ".ignore:Git Ignore"
--map-syntax ".bashrc:bash"
--map-syntax ".vimrc:vim"
--map-syntax ".cht:Markdown"
--map-syntax ".cheat:Markdown"
--map-syntax ".idea:Markdown"
--map-syntax ".ref:Markdown"
